# Generated by Django 5.2.8 on 2026-01-10 14:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OverallProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_quizzes_attempted', models.IntegerField(default=0)),
                ('total_quizzes_passed', models.IntegerField(default=0)),
                ('total_quizzes_failed', models.IntegerField(default=0)),
                ('total_score', models.FloatField(default=0)),
                ('total_marks', models.FloatField(default=0)),
                ('overall_percentage', models.FloatField(default=0)),
                ('total_time_spent', models.IntegerField(default=0, help_text='Total time spent in seconds')),
                ('highest_score', models.FloatField(default=0)),
                ('lowest_score', models.FloatField(default=0)),
                ('last_quiz_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='overall_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Overall Progress',
            },
        ),
        migrations.CreateModel(
            name='DailyProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('quizzes_attempted', models.IntegerField(default=0)),
                ('quizzes_passed', models.IntegerField(default=0)),
                ('quizzes_failed', models.IntegerField(default=0)),
                ('total_score', models.FloatField(default=0)),
                ('total_marks', models.FloatField(default=0)),
                ('average_percentage', models.FloatField(default=0)),
                ('time_spent', models.IntegerField(default=0, help_text='Time spent in seconds')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Daily Progress',
                'ordering': ['-date'],
                'unique_together': {('student', 'date')},
            },
        ),
    ]
